import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import childrenRouter from "./children.js";
import coursesRouter from "./courses.js";
import delegatesRouter from "./delegates.js";
import documentsRouter from "./documents.js";
import paymentsRouter from "./payments.js";
import promoCodesRouter from "./promo-codes.js";
import messagesRouter from "./messages.js";
import usersRouter from "./users.js";
import attendanceRouter from "./attendance.js";
import lessonsRouter from "./lessons.js";
import orgRouter from "./org.js";
import logsRouter from "./logs.js";
import enrollmentRequestsRouter from "./enrollment-requests.js";
import checkoutRouter from "./checkout.js";
import disciplinesRouter from "./disciplines.js";
import availabilityRouter from "./availability.js";
import privateBookingsRouter from "./private-bookings.js";
import privateNotificationsRouter from "./private-notifications.js";
import operatorEarningsRouter from "./operator-earnings.js";
import blacklistRouter from "./blacklist.js";
import adminSettingsRouter from "./admin-settings.js";
import accessCheckRouter from "./access-check.js";
import meetingAvailabilityRouter from "./meeting-availability.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(childrenRouter);
router.use(coursesRouter);
router.use(delegatesRouter);
router.use(documentsRouter);
router.use(paymentsRouter);
router.use(promoCodesRouter);
router.use(messagesRouter);
router.use(usersRouter);
router.use(attendanceRouter);
router.use(lessonsRouter);
router.use(orgRouter);
router.use(logsRouter);
router.use(enrollmentRequestsRouter);
router.use(checkoutRouter);
router.use(disciplinesRouter);
router.use(availabilityRouter);
router.use(privateBookingsRouter);
router.use(privateNotificationsRouter);
router.use(operatorEarningsRouter);
router.use(blacklistRouter);
router.use(adminSettingsRouter);
router.use(accessCheckRouter);
router.use(meetingAvailabilityRouter);

export default router;
