import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import childrenRouter from "./children.js";
import coursesRouter from "./courses.js";
import delegatesRouter from "./delegates.js";
import documentsRouter from "./documents.js";
import paymentsRouter from "./payments.js";
import promoCodesRouter from "./promo-codes.js";
import messagesRouter from "./messages.js";
import usersRouter from "./users.js";
import attendanceRouter from "./attendance.js";
import lessonsRouter from "./lessons.js";
import orgRouter from "./org.js";
import logsRouter from "./logs.js";
import enrollmentRequestsRouter from "./enrollment-requests.js";
import checkoutRouter from "./checkout.js";
import disciplinesRouter from "./disciplines.js";
import availabilityRouter from "./availability.js";
import privateBookingsRouter from "./private-bookings.js";
import privateNotificationsRouter from "./private-notifications.js";
import operatorEarningsRouter from "./operator-earnings.js";
import blacklistRouter from "./blacklist.js";
import adminSettingsRouter from "./admin-settings.js";
import accessCheckRouter from "./access-check.js";
import meetingAvailabilityRouter from "./meeting-availability.js";
import reimbursementsRouter from "./reimbursements.js";
import workshopProposalsRouter from "./workshop-proposals.js";
import scheduledCoursesRouter from "./scheduled-courses.js";
import courseAvailabilityRouter from "./course-availability.js";
import financeRouter from "./finance.js";
import legalRouter from "./legal.js";
import operatorClockRouter from "./operator-clock.js";
import adminKioskRouter from "./admin-kiosk.js";
import superAdminRouter from "./super-admin.js";
import billingRouter from "./billing.js";
import absencesRouter from "./absences.js";
import predictiveSubstitutesRouter from "./predictive-substitutes.js";
import adminCopilotRouter from "./admin-copilot.js";
import verifyQrRouter from "./verify-qr.js";
import identityRouter from "./identity.js";
import importRouter from "./import.js";
import securityRouter from "./security.js";
import guardianCircleRouter from "./guardian-circle.js";
import safetyScoreRouter from "./safety-score.js";
import emergencyPulseRouter from "./emergency-pulse.js";
import proximityRouter from "./proximity.js";
import marketplaceRouter from "./marketplace.js";
import systemConfigRouter from "./system-config.js";
import regionalPricingRouter from "./regional-pricing.js";
import rescueRouter from "./rescue.js";
import notificationsRouter from "./notifications.js";
import livePulseRouter from "./live-pulse.js";
import devToolsRouter from "./dev-tools.js";
import publicJoinRouter      from "./public-join.js";
import privateLessonsRouter   from "./private-lessons.js";
import notificationPrefsRouter from "./notification-prefs.js";
import calendarEventsRouter    from "./calendar-events.js";
import statsRouter             from "./stats.js";
import invitesRouter           from "./invites.js";
import eventsRouter            from "./events.js";
import locationsRouter         from "./locations.js";
import presetMessagesRouter    from "./preset-messages.js";
import waitlistRouter          from "./waitlist.js";
import employmentRouter        from "./employment.js";
import accountantPaymentsRouter from "./accountant-payments.js";
import feeEventsRouter from "./fee-events.js";
import expensesRouter from "./expenses.js";
import communicationSettingsRouter from "./communication-settings.js";
import operatorSkillsRouter      from "./operator-skills.js";
import reviewsRouter from "./reviews.js";
import enrollmentsRouter from "./enrollments.js";
import accountRouter from "./account.js";
import calendarExportRouter from "./calendar-export.js";
import directMessagesRouter from "./direct-messages.js";
import supportRouter from "./support.js";
import saFeatureAnalyticsRouter from "./sa-feature-analytics.js";
import translationsRouter from "./translations.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(childrenRouter);
router.use(coursesRouter);
router.use(delegatesRouter);
router.use(documentsRouter);
router.use(paymentsRouter);
router.use(promoCodesRouter);
router.use(messagesRouter);
router.use(usersRouter);
router.use(attendanceRouter);
router.use(lessonsRouter);
router.use(orgRouter);
router.use(logsRouter);
router.use(enrollmentRequestsRouter);
router.use(checkoutRouter);
router.use(disciplinesRouter);
router.use(availabilityRouter);
router.use(privateBookingsRouter);
router.use(privateNotificationsRouter);
router.use(operatorEarningsRouter);
router.use(blacklistRouter);
router.use(adminSettingsRouter);
router.use(accessCheckRouter);
router.use(meetingAvailabilityRouter);
router.use(reimbursementsRouter);
router.use(workshopProposalsRouter);
router.use(scheduledCoursesRouter);
router.use(courseAvailabilityRouter);
router.use(financeRouter);
router.use(legalRouter);
router.use(operatorClockRouter);
router.use(adminKioskRouter);
router.use(superAdminRouter);
router.use(billingRouter);
router.use(absencesRouter);
router.use(predictiveSubstitutesRouter);
router.use(adminCopilotRouter);
router.use(verifyQrRouter);
router.use(identityRouter);
router.use(importRouter);
router.use(securityRouter);
router.use(guardianCircleRouter);
router.use(safetyScoreRouter);
router.use(emergencyPulseRouter);
router.use(proximityRouter);
router.use(marketplaceRouter);
router.use(systemConfigRouter);
router.use(regionalPricingRouter);
router.use(rescueRouter);
router.use(notificationsRouter);
router.use(livePulseRouter);
router.use(devToolsRouter);
router.use(publicJoinRouter);
router.use(privateLessonsRouter);
router.use(notificationPrefsRouter);
router.use(calendarEventsRouter);
router.use(statsRouter);
router.use(invitesRouter);
router.use(eventsRouter);
router.use(locationsRouter);
router.use(presetMessagesRouter);
router.use(waitlistRouter);
router.use(employmentRouter);
router.use(accountantPaymentsRouter);
router.use(feeEventsRouter);
router.use(expensesRouter);
router.use(communicationSettingsRouter);
router.use(reviewsRouter);
router.use(enrollmentsRouter);
router.use(accountRouter);
router.use(calendarExportRouter);
router.use(directMessagesRouter);
router.use(supportRouter);
router.use(saFeatureAnalyticsRouter);
router.use(translationsRouter);
router.use(operatorSkillsRouter);

export default router;
