import { Ionicons } from "@expo/vector-icons";
import * as Haptics from "expo-haptics";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import React, { useState } from "react";
import {
  Alert,
  Modal,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useAuth } from "@/context/AuthContext";
import { useColors } from "@/hooks/useColors";
import { api } from "@/lib/api";

const SCHOOL_NAME = "Dance Village";

function buildInvoiceHtml(opts: {
  operatorName: string;
  month: string;
  year: number;
  hours: number;
  rate: number;
  total: number;
  lessons: number;
  students: number;
}) {
  const { operatorName, month, year, hours, rate, total, lessons, students } = opts;
  const invoiceNum = `INV-${year}-${String(Math.floor(Math.random() * 8000) + 1000)}`;
  const dateStr = new Date().toLocaleDateString("en-AU", { day: "2-digit", month: "long", year: "numeric" });
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:Helvetica,Arial,sans-serif;padding:48px 40px;color:#1a202c}
.header{display:flex;justify-content:space-between;margin-bottom:32px;padding-bottom:20px;border-bottom:3px solid #1E3A8A}
.brand-name{font-size:36px;font-weight:900;color:#1E3A8A;letter-spacing:-1px}
.brand-sub{color:#6B7280;font-size:12px;margin-top:4px}
.inv-label{font-size:24px;font-weight:800;color:#FBBF24;text-align:right}
.inv-meta{color:#6B7280;font-size:12px;text-align:right;margin-top:4px}
.parties{display:flex;gap:40px;margin-bottom:32px;background:#F8FAFF;border-radius:8px;padding:20px}
.party-label{font-size:9px;font-weight:700;color:#9CA3AF;letter-spacing:2px;text-transform:uppercase;margin-bottom:6px}
.party-name{font-size:16px;font-weight:700;color:#1E3A8A}
.party-sub{font-size:12px;color:#4B5563;margin-top:2px}
table{width:100%;border-collapse:collapse}
thead th{background:#1E3A8A;color:white;font-size:11px;font-weight:700;padding:12px 16px;text-align:left}
tbody td{padding:12px 16px;font-size:13px;border-bottom:1px solid #E5E7EB}
.total-row td{background:#FEF9C3;font-weight:800;font-size:15px;border-bottom:none}
.badge{display:inline-flex;align-items:center;background:#D1FAE5;color:#065F46;font-size:11px;font-weight:700;border-radius:20px;padding:4px 12px;margin-top:20px}
.footer{margin-top:48px;padding-top:20px;border-top:1px solid #E5E7EB;display:flex;justify-content:space-between;align-items:flex-end}
.sig-line{width:180px;border-bottom:1px solid #9CA3AF;margin-top:48px}
.sig-label{font-size:10px;color:#9CA3AF;margin-top:4px}
.footer-note{font-size:10px;color:#9CA3AF;text-align:right}
</style></head>
<body>
<div class="header">
  <div><div class="brand-name">STRIDE</div><div class="brand-sub">Dance School Management Platform</div></div>
  <div><div class="inv-label">PAYMENT REQUEST</div><div class="inv-meta">${invoiceNum}</div><div class="inv-meta">Issued: ${dateStr}</div></div>
</div>
<div class="parties">
  <div style="flex:1"><div class="party-label">From (Instructor)</div><div class="party-name">${operatorName}</div><div class="party-sub">Operator / Instructor</div><div class="party-sub">${SCHOOL_NAME}</div></div>
  <div style="flex:1"><div class="party-label">To (Administration)</div><div class="party-name">${SCHOOL_NAME} Admin</div><div class="party-sub">Finance Department</div></div>
</div>
<table>
  <thead><tr><th>Description</th><th>Quantity</th><th>Unit Rate</th><th>Amount</th></tr></thead>
  <tbody>
    <tr><td>Classes Taught — ${month} ${year}</td><td>${lessons} lessons</td><td>—</td><td>—</td></tr>
    <tr><td>Instruction Hours — ${month} ${year}</td><td>${hours} hrs</td><td>€${rate}/hr</td><td>€${(hours * rate).toFixed(2)}</td></tr>
    <tr><td>Students Instructed</td><td>${students}</td><td>—</td><td>—</td></tr>
    <tr class="total-row"><td colspan="3"><strong>TOTAL DUE</strong></td><td><strong>€${total.toFixed(2)}</strong></td></tr>
  </tbody>
</table>
<div class="badge">✓ Generated by Stride · ${dateStr}</div>
<div class="footer">
  <div><div class="sig-line"></div><div class="sig-label">Operator Signature</div></div>
  <div><div class="sig-line"></div><div class="sig-label">Authorised by Admin</div></div>
  <div><div class="footer-note">Generated by Stride Dance School Management</div><div class="footer-note">Official payment request document</div></div>
</div>
</body></html>`;
}

export default function OperatorInvoicing() {
  const { user, logout } = useAuth();
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const [selectedPeriod, setSelectedPeriod] = useState<"march" | "april">("april");
  const [generating, setGenerating] = useState(false);

  const [showChangeEmail, setShowChangeEmail] = useState(false);
  const [newEmail, setNewEmail] = useState("");
  const [deleteStep, setDeleteStep] = useState<0 | 1 | 2>(0);
  const [deleteInput, setDeleteInput] = useState("");

  const invoiceData = {
    april: { hours: 32, rate: 35, total: 1120, lessons: 22, students: 35, month: "April" },
    march:  { hours: 28, rate: 35, total: 980,  lessons: 19, students: 32, month: "March" },
  };

  const current = invoiceData[selectedPeriod];

  const handleGenerateAndShare = async () => {
    setGenerating(true);
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    try {
      const html = buildInvoiceHtml({
        operatorName: user?.name ?? "Operator",
        month: current.month,
        year: 2026,
        hours: current.hours,
        rate: current.rate,
        total: current.total,
        lessons: current.lessons,
        students: current.students,
      });

      if (Platform.OS === "web") {
        await Print.printAsync({ html });
        api.logPdfGeneration({ period: selectedPeriod, month: current.month, total_amount: current.total, action: "generated" }).catch(() => {});
      } else {
        const { uri } = await Print.printToFileAsync({ html });
        api.logPdfGeneration({ period: selectedPeriod, month: current.month, total_amount: current.total, action: "generated" }).catch(() => {});
        Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
        const canShare = await Sharing.isAvailableAsync();
        if (canShare) {
          await Sharing.shareAsync(uri, {
            mimeType: "application/pdf",
            dialogTitle: `Invoice ${current.month} 2026`,
            UTI: "com.adobe.pdf",
          });
          api.logPdfGeneration({ period: selectedPeriod, month: current.month, total_amount: current.total, action: "shared" }).catch(() => {});
        } else {
          Alert.alert("PDF Ready", "Your invoice has been generated and saved.");
        }
      }
    } catch (err) {
      Alert.alert("Error", "Could not generate PDF. Please try again.");
    } finally {
      setGenerating(false);
    }
  };

  const handleChangeEmail = () => {
    if (!newEmail.trim() || !newEmail.includes("@")) {
      Alert.alert("Invalid Email", "Please enter a valid email address.");
      return;
    }
    Alert.alert("Email Updated", `Your email has been updated to ${newEmail}.`);
    setShowChangeEmail(false);
    setNewEmail("");
  };

  const handleDeleteAccount = () => {
    if (deleteStep === 0) {
      setDeleteStep(1);
    } else if (deleteStep === 1) {
      setDeleteStep(2);
    } else {
      if (deleteInput.trim() !== "DELETE") {
        Alert.alert("Incorrect", "Please type DELETE exactly to confirm.");
        return;
      }
      Alert.alert("Account Deleted", "Your account has been removed.", [{ text: "OK", onPress: logout }]);
    }
  };

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <ScrollView
        contentContainerStyle={[styles.scroll, { paddingTop: insets.top + (Platform.OS === "web" ? 67 : 20), paddingBottom: insets.bottom + 100 }]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={[styles.pageTitle, { color: colors.primary }]}>Admin & Payroll</Text>

        <View style={[styles.profileCard, { backgroundColor: colors.primary }]}>
          <View style={styles.profileTop}>
            <View style={styles.profileAvatar}>
              <Text style={styles.profileAvatarText}>{user?.name?.charAt(0)}</Text>
            </View>
            <View style={styles.profileInfo}>
              <Text style={styles.profileName}>{user?.name}</Text>
              <Text style={styles.profileRole}>Operator / Teacher</Text>
              <Text style={styles.profileSchool}>{SCHOOL_NAME}</Text>
            </View>
          </View>
          <View style={styles.profileStats}>
            <View style={styles.profileStat}>
              <Text style={styles.profileStatNumber}>{current.lessons}</Text>
              <Text style={styles.profileStatLabel}>Lessons</Text>
            </View>
            <View style={styles.profileStatDivider} />
            <View style={styles.profileStat}>
              <Text style={styles.profileStatNumber}>{current.students}</Text>
              <Text style={styles.profileStatLabel}>Students</Text>
            </View>
            <View style={styles.profileStatDivider} />
            <View style={styles.profileStat}>
              <Text style={styles.profileStatNumber}>{current.hours}h</Text>
              <Text style={styles.profileStatLabel}>Hours</Text>
            </View>
          </View>
        </View>

        <Text style={[styles.sectionTitle, { color: colors.primary }]}>Period</Text>
        <View style={[styles.periodSelector, { backgroundColor: colors.muted }]}>
          <Pressable style={[styles.periodBtn, selectedPeriod === "april" && { backgroundColor: colors.primary }]} onPress={() => setSelectedPeriod("april")}>
            <Text style={[styles.periodBtnText, selectedPeriod === "april" && { color: "#FFF" }]}>April 2026</Text>
          </Pressable>
          <Pressable style={[styles.periodBtn, selectedPeriod === "march" && { backgroundColor: colors.primary }]} onPress={() => setSelectedPeriod("march")}>
            <Text style={[styles.periodBtnText, selectedPeriod === "march" && { color: "#FFF" }]}>March 2026</Text>
          </Pressable>
        </View>

        <View style={[styles.invoiceCard, { backgroundColor: colors.card }]}>
          <Text style={[styles.invoiceTitle, { color: colors.primary }]}>Compensation Summary</Text>
          <View style={styles.invoiceRows}>
            <View style={[styles.invoiceRow, { borderBottomColor: colors.border }]}>
              <Text style={[styles.invoiceLabel, { color: colors.mutedForeground }]}>Hours worked</Text>
              <Text style={[styles.invoiceValue, { color: colors.primary }]}>{current.hours} hrs</Text>
            </View>
            <View style={[styles.invoiceRow, { borderBottomColor: colors.border }]}>
              <Text style={[styles.invoiceLabel, { color: colors.mutedForeground }]}>Hourly rate</Text>
              <Text style={[styles.invoiceValue, { color: colors.primary }]}>€{current.rate}/h</Text>
            </View>
            <View style={[styles.invoiceRow, { borderBottomColor: colors.border }]}>
              <Text style={[styles.invoiceLabel, { color: colors.mutedForeground }]}>Lessons taught</Text>
              <Text style={[styles.invoiceValue, { color: colors.primary }]}>{current.lessons}</Text>
            </View>
          </View>
          <View style={[styles.totalRow, { backgroundColor: colors.primary }]}>
            <Text style={styles.totalLabel}>TOTAL DUE</Text>
            <Text style={styles.totalAmount}>€{current.total}</Text>
          </View>
          <Pressable
            style={[styles.generateBtn, { borderColor: colors.primary, opacity: generating ? 0.6 : 1 }]}
            onPress={handleGenerateAndShare}
            disabled={generating}
          >
            <Ionicons name={generating ? "hourglass-outline" : "document-text"} size={18} color={colors.primary} />
            <Text style={[styles.generateBtnText, { color: colors.primary }]}>
              {generating ? "GENERATING PDF..." : Platform.OS === "web" ? "PRINT / SAVE PDF" : "GENERATE & SHARE PDF"}
            </Text>
          </Pressable>
          {Platform.OS !== "web" && (
            <Text style={[styles.generateNote, { color: colors.mutedForeground }]}>
              Logs are saved to Supabase on each generate and share
            </Text>
          )}
        </View>

        <Text style={[styles.sectionTitle, { color: colors.primary }]}>Teaching Materials</Text>
        <View style={[styles.materialCard, { backgroundColor: colors.card }]}>
          <Pressable style={[styles.uploadBtn, { backgroundColor: colors.muted }]} onPress={() => Alert.alert("Upload", "Select a file to share with your students.")}>
            <Ionicons name="cloud-upload-outline" size={24} color={colors.primary} />
            <Text style={[styles.uploadBtnText, { color: colors.primary }]}>Upload MP3 / PDF / Script</Text>
          </Pressable>
          {[
            { name: "Recital Script 2026.pdf", date: "05 Apr", type: "pdf" },
            { name: "Dance Music Base.mp3",    date: "02 Apr", type: "mp3" },
          ].map((file, i) => (
            <View key={i} style={[styles.fileRow, { borderTopColor: colors.border }]}>
              <Ionicons name={file.type === "pdf" ? "document-text" : "musical-notes"} size={18} color={colors.primary} />
              <Text style={[styles.fileName, { color: colors.foreground }]}>{file.name}</Text>
              <Text style={[styles.fileDate, { color: colors.mutedForeground }]}>{file.date}</Text>
            </View>
          ))}
        </View>

        <View style={[styles.settingsCard, { backgroundColor: colors.card }]}>
          <Pressable style={styles.settingsItem} onPress={() => Alert.alert("Password", "A reset link has been sent to your email.")}>
            <Ionicons name="lock-closed-outline" size={20} color={colors.primary} />
            <Text style={[styles.settingsLabel, { color: colors.foreground }]}>Change Password</Text>
            <Ionicons name="chevron-forward" size={16} color={colors.mutedForeground} />
          </Pressable>
          <Pressable style={[styles.settingsItem, { borderTopWidth: 1, borderTopColor: colors.border }]} onPress={() => setShowChangeEmail(true)}>
            <Ionicons name="mail-outline" size={20} color={colors.primary} />
            <Text style={[styles.settingsLabel, { color: colors.foreground }]}>Change Email</Text>
            <Ionicons name="chevron-forward" size={16} color={colors.mutedForeground} />
          </Pressable>
          <Pressable style={[styles.settingsItem, { borderTopWidth: 1, borderTopColor: colors.border }]} onPress={logout}>
            <Ionicons name="log-out-outline" size={20} color="#F59E0B" />
            <Text style={[styles.settingsLabel, { color: "#F59E0B" }]}>Log Out</Text>
            <Ionicons name="chevron-forward" size={16} color="#F59E0B" />
          </Pressable>
          <Pressable
            style={[styles.settingsItem, { borderTopWidth: 1, borderTopColor: colors.border }]}
            onPress={handleDeleteAccount}
          >
            <Ionicons name="trash-outline" size={20} color="#EF4444" />
            <Text style={[styles.settingsLabel, { color: "#EF4444" }]}>
              {deleteStep === 0 ? "Delete Account" : deleteStep === 1 ? "Tap again to confirm" : "Type DELETE to confirm"}
            </Text>
            <Ionicons name="chevron-forward" size={16} color="#EF4444" />
          </Pressable>
        </View>

        {deleteStep === 2 && (
          <View style={[styles.deleteConfirmCard, { backgroundColor: "#FEF2F2", borderColor: "#FECACA" }]}>
            <Text style={styles.deleteConfirmTitle}>⚠️ Final Confirmation</Text>
            <Text style={styles.deleteConfirmBody}>
              This action is permanent and cannot be undone. Type DELETE below and tap the button above to proceed.
            </Text>
            <TextInput
              style={[styles.deleteInput, { borderColor: "#FECACA", color: "#EF4444" }]}
              value={deleteInput}
              onChangeText={setDeleteInput}
              placeholder="Type DELETE here"
              placeholderTextColor="#FCA5A5"
              autoCapitalize="characters"
            />
            <Pressable style={styles.deleteCancelBtn} onPress={() => { setDeleteStep(0); setDeleteInput(""); }}>
              <Text style={[styles.deleteCancelText, { color: colors.primary }]}>Cancel</Text>
            </Pressable>
          </View>
        )}
      </ScrollView>

      <Modal visible={showChangeEmail} transparent animationType="slide" onRequestClose={() => setShowChangeEmail(false)}>
        <View style={styles.modalOverlay}>
          <View style={[styles.modalCard, { backgroundColor: colors.card }]}>
            <Text style={[styles.modalTitle, { color: colors.primary }]}>Change Email</Text>
            <Text style={[styles.modalSub, { color: colors.mutedForeground }]}>Enter your new email address below.</Text>
            <TextInput
              style={[styles.emailInput, { borderColor: colors.border, color: colors.foreground, backgroundColor: colors.muted }]}
              value={newEmail}
              onChangeText={setNewEmail}
              placeholder="new@email.com"
              placeholderTextColor={colors.mutedForeground}
              keyboardType="email-address"
              autoCapitalize="none"
            />
            <View style={styles.modalActions}>
              <Pressable style={[styles.modalCancelBtn, { backgroundColor: colors.muted }]} onPress={() => { setShowChangeEmail(false); setNewEmail(""); }}>
                <Text style={[styles.modalCancelText, { color: colors.mutedForeground }]}>Cancel</Text>
              </Pressable>
              <Pressable style={[styles.modalConfirmBtn, { backgroundColor: colors.primary }]} onPress={handleChangeEmail}>
                <Text style={styles.modalConfirmText}>Update Email</Text>
              </Pressable>
            </View>
          </View>
        </View>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  scroll: { paddingHorizontal: 20 },
  pageTitle: { fontSize: 28, fontWeight: "800", marginBottom: 20 },
  profileCard: { borderRadius: 20, padding: 20, marginBottom: 24 },
  profileTop: { flexDirection: "row", gap: 16, marginBottom: 20 },
  profileAvatar: { width: 60, height: 60, borderRadius: 30, backgroundColor: "rgba(255,255,255,0.2)", alignItems: "center", justifyContent: "center" },
  profileAvatarText: { color: "#FFF", fontSize: 26, fontWeight: "700" },
  profileInfo: { flex: 1, justifyContent: "center" },
  profileName: { color: "#FFF", fontSize: 20, fontWeight: "700" },
  profileRole: { color: "rgba(255,255,255,0.8)", fontSize: 13, marginTop: 2 },
  profileSchool: { color: "#FBBF24", fontSize: 13, fontWeight: "600", marginTop: 2 },
  profileStats: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(255,255,255,0.15)", borderRadius: 14, padding: 16 },
  profileStat: { flex: 1, alignItems: "center" },
  profileStatNumber: { color: "#FFF", fontSize: 24, fontWeight: "800" },
  profileStatLabel: { color: "rgba(255,255,255,0.7)", fontSize: 12 },
  profileStatDivider: { width: 1, height: 36, backgroundColor: "rgba(255,255,255,0.2)" },
  sectionTitle: { fontSize: 17, fontWeight: "700", marginBottom: 12 },
  periodSelector: { flexDirection: "row", borderRadius: 12, padding: 4, marginBottom: 16, gap: 4 },
  periodBtn: { flex: 1, borderRadius: 10, paddingVertical: 10, alignItems: "center" },
  periodBtnText: { fontSize: 14, fontWeight: "600", color: "#6B7BA4" },
  invoiceCard: { borderRadius: 18, overflow: "hidden", marginBottom: 24, shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 12, elevation: 4 },
  invoiceTitle: { fontSize: 17, fontWeight: "700", padding: 18, paddingBottom: 12 },
  invoiceRows: { paddingHorizontal: 18 },
  invoiceRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 12, borderBottomWidth: 1 },
  invoiceLabel: { fontSize: 14 },
  invoiceValue: { fontSize: 14, fontWeight: "700" },
  totalRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 18 },
  totalLabel: { color: "#FFF", fontSize: 13, fontWeight: "700", letterSpacing: 1 },
  totalAmount: { color: "#FFF", fontSize: 26, fontWeight: "800" },
  generateBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10, margin: 16, marginBottom: 8, borderRadius: 12, paddingVertical: 14, borderWidth: 2 },
  generateBtnText: { fontWeight: "700", fontSize: 14 },
  generateNote: { fontSize: 11, textAlign: "center", marginBottom: 16, paddingHorizontal: 16 },
  materialCard: { borderRadius: 18, padding: 16, marginBottom: 20 },
  uploadBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10, borderRadius: 12, paddingVertical: 16, marginBottom: 12 },
  uploadBtnText: { fontWeight: "600", fontSize: 14 },
  fileRow: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 12, borderTopWidth: 1 },
  fileName: { flex: 1, fontSize: 13 },
  fileDate: { fontSize: 12 },
  settingsCard: { borderRadius: 16, overflow: "hidden", marginBottom: 20 },
  settingsItem: { flexDirection: "row", alignItems: "center", padding: 16, gap: 12 },
  settingsLabel: { flex: 1, fontSize: 15, fontWeight: "500" },
  deleteConfirmCard: { borderRadius: 16, padding: 20, marginBottom: 24, borderWidth: 1 },
  deleteConfirmTitle: { fontSize: 16, fontWeight: "700", color: "#EF4444", marginBottom: 8 },
  deleteConfirmBody: { fontSize: 13, color: "#7F1D1D", lineHeight: 20, marginBottom: 14 },
  deleteInput: { borderWidth: 1.5, borderRadius: 12, padding: 14, fontSize: 15, fontWeight: "700", marginBottom: 12 },
  deleteCancelBtn: { alignItems: "center", paddingVertical: 10 },
  deleteCancelText: { fontSize: 14, fontWeight: "600" },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end" },
  modalCard: { borderRadius: 24, padding: 24, margin: 16 },
  modalTitle: { fontSize: 20, fontWeight: "700", marginBottom: 6 },
  modalSub: { fontSize: 14, marginBottom: 20 },
  emailInput: { borderWidth: 1.5, borderRadius: 14, padding: 14, fontSize: 15, marginBottom: 20 },
  modalActions: { flexDirection: "row", gap: 12 },
  modalCancelBtn: { flex: 1, borderRadius: 14, paddingVertical: 14, alignItems: "center" },
  modalCancelText: { fontSize: 15, fontWeight: "600" },
  modalConfirmBtn: { flex: 1, borderRadius: 14, paddingVertical: 14, alignItems: "center" },
  modalConfirmText: { color: "#FFF", fontSize: 15, fontWeight: "700" },
});
