// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/stride-promo/index.tsx": () => import("../components/mockups/stride-promo/index.tsx"),
  "./components/mockups/stride-promo/scenes/Scene1.tsx": () => import("../components/mockups/stride-promo/scenes/Scene1.tsx"),
  "./components/mockups/stride-promo/scenes/Scene2.tsx": () => import("../components/mockups/stride-promo/scenes/Scene2.tsx"),
  "./components/mockups/stride-promo/scenes/Scene3.tsx": () => import("../components/mockups/stride-promo/scenes/Scene3.tsx"),
  "./components/mockups/stride-promo/scenes/Scene4.tsx": () => import("../components/mockups/stride-promo/scenes/Scene4.tsx"),
  "./components/mockups/stride-promo/scenes/Scene5.tsx": () => import("../components/mockups/stride-promo/scenes/Scene5.tsx"),
  "./components/mockups/stride-promo/scenes/Scene6.tsx": () => import("../components/mockups/stride-promo/scenes/Scene6.tsx"),
  "./components/mockups/stride-promo/scenes/Scene7.tsx": () => import("../components/mockups/stride-promo/scenes/Scene7.tsx")
};
