// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/stride-promo/index.tsx": () => import("../components/mockups/stride-promo/index.tsx"),
  "./components/mockups/marketing/admin.tsx": () => import("../components/mockups/marketing/admin.tsx"),
  "./components/mockups/marketing/brochure.tsx": () => import("../components/mockups/marketing/brochure.tsx"),
  "./components/mockups/marketing/instagram-post.tsx": () => import("../components/mockups/marketing/instagram-post.tsx"),
  "./components/mockups/marketing/instagram-story.tsx": () => import("../components/mockups/marketing/instagram-story.tsx"),
  "./components/mockups/marketing/linkedin-banner.tsx": () => import("../components/mockups/marketing/linkedin-banner.tsx"),
  "./components/mockups/marketing/operator.tsx": () => import("../components/mockups/marketing/operator.tsx"),
  "./components/mockups/marketing/parent.tsx": () => import("../components/mockups/marketing/parent.tsx"),
  "./components/mockups/stride-promo/scenes/Scene1.tsx": () => import("../components/mockups/stride-promo/scenes/Scene1.tsx"),
  "./components/mockups/stride-promo/scenes/Scene2.tsx": () => import("../components/mockups/stride-promo/scenes/Scene2.tsx"),
  "./components/mockups/stride-promo/scenes/Scene3.tsx": () => import("../components/mockups/stride-promo/scenes/Scene3.tsx"),
  "./components/mockups/stride-promo/scenes/Scene4.tsx": () => import("../components/mockups/stride-promo/scenes/Scene4.tsx"),
  "./components/mockups/stride-promo/scenes/Scene5.tsx": () => import("../components/mockups/stride-promo/scenes/Scene5.tsx"),
  "./components/mockups/stride-promo/scenes/Scene6.tsx": () => import("../components/mockups/stride-promo/scenes/Scene6.tsx"),
  "./components/mockups/stride-promo/scenes/Scene7.tsx": () => import("../components/mockups/stride-promo/scenes/Scene7.tsx")
};
