// Stride Service Worker — auto-generated by pwa-patch.js
var CACHE_NAME = 'stride-pwa-d436f2a5';

// Activate immediately — do not wait for existing tabs to close
self.addEventListener('install', function(event) {
  self.skipWaiting();
});

self.addEventListener('activate', function(event) {
  // Claim all open clients immediately so updates take effect right away
  event.waitUntil(
    caches.keys().then(function(keys) {
      return Promise.all(
        keys.filter(function(k) { return k !== CACHE_NAME; })
            .map(function(k) { return caches.delete(k); })
      );
    }).then(function() {
      return self.clients.claim();
    })
  );
});

self.addEventListener('fetch', function(event) {
  var url = new URL(event.request.url);

  // Only intercept same-origin /app/ requests
  if (url.origin !== location.origin) return;
  if (!url.pathname.startsWith('/app/')) return;

  // Never cache: HTML pages, sw.js itself, version.json
  if (
    event.request.mode === 'navigate' ||
    url.pathname.endsWith('sw.js') ||
    url.pathname.endsWith('version.json') ||
    url.pathname.endsWith('.html')
  ) {
    event.respondWith(fetch(event.request));
    return;
  }

  // Cache-first for content-hashed assets (bundles, fonts, images)
  event.respondWith(
    caches.open(CACHE_NAME).then(function(cache) {
      return cache.match(event.request).then(function(cached) {
        if (cached) return cached;
        return fetch(event.request).then(function(response) {
          if (response.ok) cache.put(event.request, response.clone());
          return response;
        });
      });
    })
  );
});
