// Stride Service Worker — auto-generated by pwa-patch.js
var CACHE_NAME = 'stride-pwa-a91e2e03';

// Activate immediately — do not wait for existing tabs to close
self.addEventListener('install', function(event) {
  self.skipWaiting();
});

self.addEventListener('activate', function(event) {
  // Purge ALL old caches and claim clients immediately
  event.waitUntil(
    caches.keys()
      .then(function(keys) { return Promise.all(keys.map(function(k) { return caches.delete(k); })); })
      .then(function() { return self.clients.claim(); })
  );
});

// No fetch interception — the browser handles all requests normally.
// Auto-update is handled by version.json polling in index.html.
