import { relations } from "drizzle-orm";
import { disciplines }    from "./disciplines";
import { bookings }       from "./bookings";
import { notifications }  from "./notifications";

// ── disciplines ───────────────────────────────────────────────────────────────

export const disciplinesRelations = relations(disciplines, ({ many }) => ({
  /** All bookings for this discipline */
  bookings: many(bookings),
}));

// ── bookings ──────────────────────────────────────────────────────────────────

export const bookingsRelations = relations(bookings, ({ one, many }) => ({
  /** The discipline being taught */
  discipline: one(disciplines, {
    fields:     [bookings.disciplineId],
    references: [disciplines.id],
  }),
  /** Notifications generated by / for this booking */
  notifications: many(notifications),
}));

// ── notifications ─────────────────────────────────────────────────────────────

export const notificationsRelations = relations(notifications, ({ one }) => ({
  /** The booking this notification relates to (optional) */
  booking: one(bookings, {
    fields:     [notifications.bookingId],
    references: [bookings.id],
  }),
}));
